---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sources
namespace: flux-system

resources:
  - flux-community.yaml
  - proxmox-csi.yaml
  - metrics-server.yaml
  - tailscale.yaml
  - cloudflare.yaml
  - jetstack.yaml
  - external-dns.yaml
  - haproxytech.yaml
  - envoy-gateway.yaml
  - metallb.yaml
  - prometheus-community.yaml
  - grafana.yaml
  - elastic.yaml
  - fluent.yaml
  - kedacore.yaml
  - aquasecurity.yaml
  - raoulx24.yaml
  - podinfo.yaml
