---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tailscale-crds
namespace: tailscale-operator

labels:
  - includeSelectors: true
    pairs:
      flux.kub3.uk/organisation: n3tuk
      flux.kub3.uk/repository: infra-flux
      flux.kub3.uk/kustomization: tailscale-crds
      flux.kub3.uk/name: tailscale
      flux.kub3.uk/application: tailscale
      flux.kub3.uk/component: operator
      flux.kub3.uk/managed-by: kustomization

resources:
  - resources.yaml
