---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: prometheus-metrics
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: envoy-gateway
      name: tailnet
  hostnames:
    - prometheus.${cluster_domain}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - kind: Service
          name: prometheus
          port: 9090
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: prometheus
  namespace: prometheus-metrics
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: prometheus
  loadBalancer:
    # Use the source address as the selector of which Prometheus Pod to direct
    # traffic to to limit any subtle differences between instances affecting
    # queries as each instance scrapes and saves results at different times
    type: ConsistentHash
    consistentHash:
      type: Header
      header:
        name: X-Forwarded-For
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: prometheus
  namespace: prometheus-metrics
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: prometheus
  oidc:
    provider:
      issuer: ${prometheus_issuer_url}
    clientID: ${prometheus_client_id}
    clientSecret:
      name: prometheus-oidc-credentials
    redirectURL: https://prometheus.${cluster_domain}/oauth2/callback
    logoutPath: /logout
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-oidc-credentials
  namespace: prometheus-metrics
stringData:
  client-id: ${prometheus_client_id}
  client-secret: ${prometheus_client_secret}
