---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alertmanager
  namespace: prometheus-metrics
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: envoy-gateway
      name: tailscale
  hostnames:
    - alerts.${cluster_domain}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - kind: Service
          name: alertmanager
          port: 9093
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: alertmanager
  namespace: prometheus-metrics
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: alertmanager
  oidc:
    provider:
      issuer: ${alertmanager_issuer_url}
    clientID: ${alertmanager_client_id}
    clientSecret:
      name: alertmanager-oidc-credentials
    redirectURL: https://alerts.${cluster_domain}/oauth2/callback
    logoutPath: /logout
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-oidc-credentials
  namespace: prometheus-metrics
stringData:
  client-id: ${alertmanager_client_id}
  client-secret: ${alertmanager_client_secret}
