---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: podinfo
  namespace: app-podinfo
  annotations:
    external-dns.alpha.kubernetes.io/target: ${cloudflare_tunnel}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: envoy-gateway
      name: external
  hostnames:
    - podinfo.${t3st_domain}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - kind: Service
          name: podinfo
          port: 9898
