---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gateways
  namespace: flux-system
namespace: envoy-gateway

labels:
  - includeSelectors: false
    pairs:
      flux.kub3.uk/organisation: n3tuk
      flux.kub3.uk/repository: infra-flux
      flux.kub3.uk/kustomization: envoy-gateway
      flux.kub3.uk/name: envoy-gateway
      flux.kub3.uk/application: envoy-gateway
      flux.kub3.uk/component: gateways
      flux.kub3.uk/managed-by: kustomization

resources:
  - certificates.yaml
  - external.yaml
  - internal.yaml
  - tailscale.yaml
  - https-redirect.yaml
